// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSkillLensReferences(arg1) {
  return window['go']['main']['App']['CheckSkillLensReferences'](arg1);
}

export function CreateAcademicCredential(arg1) {
  return window['go']['main']['App']['CreateAcademicCredential'](arg1);
}

export function CreateBullet(arg1, arg2) {
  return window['go']['main']['App']['CreateBullet'](arg1, arg2);
}

export function CreateCertification(arg1) {
  return window['go']['main']['App']['CreateCertification'](arg1);
}

export function CreateDescriptor(arg1) {
  return window['go']['main']['App']['CreateDescriptor'](arg1);
}

export function CreateProfileLink(arg1) {
  return window['go']['main']['App']['CreateProfileLink'](arg1);
}

export function CreateSkill(arg1) {
  return window['go']['main']['App']['CreateSkill'](arg1);
}

export function CreateSkillCategory(arg1) {
  return window['go']['main']['App']['CreateSkillCategory'](arg1);
}

export function CreateSummary(arg1) {
  return window['go']['main']['App']['CreateSummary'](arg1);
}

export function CreateWorkHistory(arg1) {
  return window['go']['main']['App']['CreateWorkHistory'](arg1);
}

export function DeleteAcademicCredential(arg1) {
  return window['go']['main']['App']['DeleteAcademicCredential'](arg1);
}

export function DeleteBullet(arg1) {
  return window['go']['main']['App']['DeleteBullet'](arg1);
}

export function DeleteCertification(arg1) {
  return window['go']['main']['App']['DeleteCertification'](arg1);
}

export function DeleteDescriptor(arg1) {
  return window['go']['main']['App']['DeleteDescriptor'](arg1);
}

export function DeleteProfileLink(arg1) {
  return window['go']['main']['App']['DeleteProfileLink'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteSkillCategory(arg1) {
  return window['go']['main']['App']['DeleteSkillCategory'](arg1);
}

export function DeleteSummary(arg1) {
  return window['go']['main']['App']['DeleteSummary'](arg1);
}

export function DeleteWorkHistory(arg1) {
  return window['go']['main']['App']['DeleteWorkHistory'](arg1);
}

export function GetCompetenceLevels() {
  return window['go']['main']['App']['GetCompetenceLevels']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetWorkHistory(arg1) {
  return window['go']['main']['App']['GetWorkHistory'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAcademicCredentials() {
  return window['go']['main']['App']['ListAcademicCredentials']();
}

export function ListCertifications() {
  return window['go']['main']['App']['ListCertifications']();
}

export function ListDescriptors() {
  return window['go']['main']['App']['ListDescriptors']();
}

export function ListProfileLinks() {
  return window['go']['main']['App']['ListProfileLinks']();
}

export function ListSkillCategories() {
  return window['go']['main']['App']['ListSkillCategories']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListSkillsByCategory() {
  return window['go']['main']['App']['ListSkillsByCategory']();
}

export function ListSummaries() {
  return window['go']['main']['App']['ListSummaries']();
}

export function ListWorkHistory() {
  return window['go']['main']['App']['ListWorkHistory']();
}

export function RenameSkillCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameSkillCategory'](arg1, arg2);
}

export function ReorderAcademicCredentials(arg1) {
  return window['go']['main']['App']['ReorderAcademicCredentials'](arg1);
}

export function ReorderBullets(arg1, arg2) {
  return window['go']['main']['App']['ReorderBullets'](arg1, arg2);
}

export function ReorderCertifications(arg1) {
  return window['go']['main']['App']['ReorderCertifications'](arg1);
}

export function ReorderDescriptors(arg1) {
  return window['go']['main']['App']['ReorderDescriptors'](arg1);
}

export function ReorderProfileLinks(arg1) {
  return window['go']['main']['App']['ReorderProfileLinks'](arg1);
}

export function ReorderSkillCategories(arg1) {
  return window['go']['main']['App']['ReorderSkillCategories'](arg1);
}

export function ReorderWorkHistory(arg1) {
  return window['go']['main']['App']['ReorderWorkHistory'](arg1);
}

export function SplitBulletText(arg1) {
  return window['go']['main']['App']['SplitBulletText'](arg1);
}

export function SplitSkillsText(arg1) {
  return window['go']['main']['App']['SplitSkillsText'](arg1);
}

export function UpdateAcademicCredential(arg1, arg2) {
  return window['go']['main']['App']['UpdateAcademicCredential'](arg1, arg2);
}

export function UpdateBullet(arg1, arg2) {
  return window['go']['main']['App']['UpdateBullet'](arg1, arg2);
}

export function UpdateCertification(arg1, arg2) {
  return window['go']['main']['App']['UpdateCertification'](arg1, arg2);
}

export function UpdateDescriptor(arg1, arg2) {
  return window['go']['main']['App']['UpdateDescriptor'](arg1, arg2);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateProfileLink(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileLink'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2);
}

export function UpdateSummary(arg1, arg2) {
  return window['go']['main']['App']['UpdateSummary'](arg1, arg2);
}

export function UpdateWorkHistory(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkHistory'](arg1, arg2);
}
