// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function BrowseForDataDirectory():Promise<string>;

export function CheckAcademicLensReferences(arg1:number):Promise<Array<string>>;

export function CheckBulletLensReferences(arg1:number):Promise<Array<string>>;

export function CheckCertLensReferences(arg1:number):Promise<Array<string>>;

export function CheckCoreExpertiseLensReferences(arg1:number):Promise<Array<string>>;

export function CheckDescriptorLensReferences(arg1:number):Promise<Array<string>>;

export function CheckSkillLensReferences(arg1:number):Promise<Array<string>>;

export function CheckSummaryLensReferences(arg1:number):Promise<Array<string>>;

export function CheckWorkHistoryLensReferences(arg1:number):Promise<Array<string>>;

export function CleanupOldExports(arg1:number):Promise<number>;

export function CreateAcademicCredential(arg1:domain.AcademicInput):Promise<domain.AcademicCredential>;

export function CreateApplication(arg1:domain.ApplicationInput):Promise<domain.JobApplication>;

export function CreateBullet(arg1:number,arg2:string,arg3:string):Promise<domain.AchievementBullet>;

export function CreateCertification(arg1:domain.CertificationInput):Promise<domain.Certification>;

export function CreateCoreExpertise(arg1:string):Promise<domain.CoreExpertise>;

export function CreateCoverLetter(arg1:domain.CoverLetterInput):Promise<domain.CoverLetter>;

export function CreateDescriptor(arg1:string):Promise<domain.RoleDescriptor>;

export function CreateDocumentTemplate(arg1:domain.DocumentTemplateInput):Promise<domain.DocumentTemplate>;

export function CreateExport(arg1:domain.ExportRequest):Promise<domain.ResumeExport>;

export function CreateLens(arg1:domain.LensInput):Promise<domain.Lens>;

export function CreateProfileLink(arg1:domain.ProfileLinkInput):Promise<domain.ProfileLink>;

export function CreateSkill(arg1:domain.SkillInput):Promise<domain.Skill>;

export function CreateSkillCategory(arg1:string):Promise<domain.SkillCategory>;

export function CreateSummary(arg1:domain.SummaryInput):Promise<domain.ProfessionalSummary>;

export function CreateTemplateElement(arg1:number,arg2:domain.TemplateElementInput):Promise<domain.TemplateElement>;

export function CreateWorkHistory(arg1:domain.WorkHistoryInput):Promise<domain.WorkHistoryEntry>;

export function DeleteAcademicCredential(arg1:number):Promise<void>;

export function DeleteApplication(arg1:number):Promise<void>;

export function DeleteBullet(arg1:number):Promise<void>;

export function DeleteCertification(arg1:number):Promise<void>;

export function DeleteCoreExpertise(arg1:number):Promise<void>;

export function DeleteCoverLetter(arg1:number):Promise<void>;

export function DeleteDescriptor(arg1:number):Promise<void>;

export function DeleteDocumentTemplate(arg1:number):Promise<void>;

export function DeleteLens(arg1:number):Promise<void>;

export function DeleteProfileLink(arg1:number):Promise<void>;

export function DeleteSkill(arg1:number):Promise<void>;

export function DeleteSkillCategory(arg1:number):Promise<void>;

export function DeleteSummary(arg1:number):Promise<void>;

export function DeleteTemplateElement(arg1:number):Promise<void>;

export function DeleteWorkHistory(arg1:number):Promise<void>;

export function DuplicateDocumentTemplate(arg1:number,arg2:string):Promise<domain.DocumentTemplate>;

export function ExportAllData(arg1:string):Promise<string>;

export function ExportCoverLetter(arg1:number):Promise<string>;

export function ExportTemplate(arg1:number,arg2:string):Promise<void>;

export function GetApplicationHistory(arg1:number):Promise<Array<domain.StatusChange>>;

export function GetApplicationPromptValues(arg1:number,arg2:number):Promise<Record<string, string>>;

export function GetApplicationStatuses():Promise<Array<string>>;

export function GetBackupSettings():Promise<domain.BackupSettings>;

export function GetCompetenceLevels():Promise<Array<domain.CompetenceLevel>>;

export function GetDataDirectory():Promise<string>;

export function GetDocumentTemplate(arg1:number):Promise<domain.TemplateDetail>;

export function GetFitIndicators():Promise<Array<string>>;

export function GetLens(arg1:number):Promise<domain.LensDetail>;

export function GetLensExportSelections(arg1:number):Promise<domain.ExportRequest>;

export function GetProfile():Promise<domain.UserProfile>;

export function GetSkillLensTags(arg1:number):Promise<Array<number>>;

export function GetWorkHistory(arg1:number):Promise<domain.WorkHistoryEntry>;

export function Greet(arg1:string):Promise<string>;

export function ImportAllData(arg1:string):Promise<void>;

export function ImportCSV(arg1:string,arg2:string):Promise<domain.ImportResult>;

export function ImportJSON(arg1:string,arg2:string):Promise<domain.ImportResult>;

export function ImportTemplate(arg1:string):Promise<domain.DocumentTemplate>;

export function ListAcademicCredentials():Promise<Array<domain.AcademicCredential>>;

export function ListApplications():Promise<Array<domain.JobApplication>>;

export function ListCertifications():Promise<Array<domain.Certification>>;

export function ListCoreExpertise():Promise<Array<domain.CoreExpertise>>;

export function ListCoverLetters():Promise<Array<domain.CoverLetter>>;

export function ListDescriptors():Promise<Array<domain.RoleDescriptor>>;

export function ListDocumentTemplates():Promise<Array<domain.DocumentTemplate>>;

export function ListExports():Promise<Array<domain.ResumeExport>>;

export function ListLenses():Promise<Array<domain.Lens>>;

export function ListProfileLinks():Promise<Array<domain.ProfileLink>>;

export function ListSkillCategories():Promise<Array<domain.SkillCategory>>;

export function ListSkills():Promise<Array<domain.Skill>>;

export function ListSkillsByCategory():Promise<Array<domain.SkillCategoryWithSkills>>;

export function ListSkillsWithLensTags():Promise<Array<domain.SkillWithTags>>;

export function ListSummaries():Promise<Array<domain.ProfessionalSummary>>;

export function ListTemplates():Promise<Array<domain.ResumeTemplate>>;

export function ListWorkHistory():Promise<Array<domain.WorkHistoryEntry>>;

export function OpenDataDirectory():Promise<void>;

export function OpenExportFile(arg1:number):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OverwriteExport(arg1:number,arg2:domain.ExportRequest):Promise<domain.ResumeExport>;

export function ParseTemplateVariables(arg1:number):Promise<domain.TemplateVariables>;

export function PrepareApplicationUploadFolder(arg1:number):Promise<string>;

export function PreviewExport(arg1:domain.ExportRequest):Promise<string>;

export function PreviewTemplate(arg1:number):Promise<string>;

export function RenameSkillCategory(arg1:number,arg2:string):Promise<domain.SkillCategory>;

export function ReorderAcademicCredentials(arg1:Array<number>):Promise<void>;

export function ReorderBullets(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderCertifications(arg1:Array<number>):Promise<void>;

export function ReorderCoreExpertise(arg1:Array<number>):Promise<void>;

export function ReorderDescriptors(arg1:Array<number>):Promise<void>;

export function ReorderProfileLinks(arg1:Array<number>):Promise<void>;

export function ReorderSkillCategories(arg1:Array<number>):Promise<void>;

export function ReorderTemplateElements(arg1:number,arg2:any,arg3:Array<number>):Promise<void>;

export function ReorderWorkHistory(arg1:Array<number>):Promise<void>;

export function SaveApplicationPromptValues(arg1:number,arg2:number,arg3:Record<string, string>):Promise<void>;

export function SearchApplications(arg1:string):Promise<Array<domain.JobApplication>>;

export function SetDataDirectory(arg1:string):Promise<void>;

export function SetLensAcademics(arg1:number,arg2:Array<number>):Promise<void>;

export function SetLensBullets(arg1:number,arg2:Array<domain.LensBulletItem>):Promise<void>;

export function SetLensCerts(arg1:number,arg2:Array<number>):Promise<void>;

export function SetLensCoreExpertise(arg1:number,arg2:Array<domain.LensCoreExpertiseItem>):Promise<void>;

export function SetLensDescriptors(arg1:number,arg2:Array<domain.LensDescriptorItem>):Promise<void>;

export function SetLensSkills(arg1:number,arg2:Array<domain.LensSkillItem>):Promise<void>;

export function SetLensSummaries(arg1:number,arg2:Array<domain.LensSummaryItem>):Promise<void>;

export function SetLensWorkHistory(arg1:number,arg2:Array<domain.LensWorkHistoryItem>):Promise<void>;

export function SetSkillLensTags(arg1:number,arg2:Array<number>):Promise<void>;

export function SplitBulletText(arg1:string):Promise<Array<string>>;

export function SplitCoreExpertiseText(arg1:string):Promise<Array<string>>;

export function SplitSkillsText(arg1:string):Promise<Array<string>>;

export function UpdateAcademicCredential(arg1:number,arg2:domain.AcademicInput):Promise<domain.AcademicCredential>;

export function UpdateApplication(arg1:number,arg2:domain.ApplicationInput):Promise<domain.JobApplication>;

export function UpdateApplicationFit(arg1:number,arg2:string):Promise<domain.JobApplication>;

export function UpdateApplicationStatus(arg1:number,arg2:string):Promise<domain.JobApplication>;

export function UpdateBackupSettings(arg1:domain.BackupSettings):Promise<void>;

export function UpdateBullet(arg1:number,arg2:string):Promise<domain.AchievementBullet>;

export function UpdateCertification(arg1:number,arg2:domain.CertificationInput):Promise<domain.Certification>;

export function UpdateCoreExpertise(arg1:number,arg2:string):Promise<domain.CoreExpertise>;

export function UpdateCoverLetter(arg1:number,arg2:domain.CoverLetterInput):Promise<domain.CoverLetter>;

export function UpdateDescriptor(arg1:number,arg2:string):Promise<domain.RoleDescriptor>;

export function UpdateDocumentTemplate(arg1:number,arg2:domain.DocumentTemplateInput):Promise<domain.DocumentTemplate>;

export function UpdateLens(arg1:number,arg2:domain.LensInput):Promise<domain.Lens>;

export function UpdateProfile(arg1:domain.UserProfile):Promise<domain.UserProfile>;

export function UpdateProfileLink(arg1:number,arg2:domain.ProfileLinkInput):Promise<domain.ProfileLink>;

export function UpdateSkill(arg1:number,arg2:domain.SkillInput):Promise<domain.Skill>;

export function UpdateSummary(arg1:number,arg2:domain.SummaryInput):Promise<domain.ProfessionalSummary>;

export function UpdateTemplateElement(arg1:number,arg2:domain.TemplateElementInput):Promise<domain.TemplateElement>;

export function UpdateWorkHistory(arg1:number,arg2:domain.WorkHistoryInput):Promise<domain.WorkHistoryEntry>;
